-- db/triggers/03_log_pump_operations.sql
--
-- TRIGGER 3 (OBLIGATOIRE) : Enregistrer automatiquement les opérations des pompes
--
-- Ce que vous devez faire ici :
-- 1. USE urba_drain;
-- 2. Changer le délimiteur : DELIMITER //
-- 3. Créer un trigger trg_log_pump_operation
--    - Déclenché AFTER UPDATE ON pumps
--    - FOR EACH ROW
--
-- 4. Logique du trigger :
--    - Si NEW.status = 'ACTIVE' ET OLD.status != 'ACTIVE'
--      Alors INSERT INTO pump_operations :
--      * pump_id = NEW.id
--      * operation_type = 'START'
--      * notes = 'Pompe activée automatiquement'
--
--    - Si NEW.status = 'INACTIVE' ET OLD.status = 'ACTIVE'
--      Alors INSERT INTO pump_operations :
--      * pump_id = NEW.id
--      * operation_type = 'STOP'
--      * notes = 'Pompe désactivée'
--
-- Ce trigger enregistre automatiquement l'historique des opérations
-- quand le statut d'une pompe change
--
-- 5. Terminer avec END// et DELIMITER ;
