-- db/schema/01_create_tables.sql
--
-- Ce fichier crée le schéma de la base de données
--
-- Ce que vous devez faire ici :
-- 1. Créer la base de données urba_drain si elle n'existe pas
-- 2. Utiliser cette base : USE urba_drain;
--
-- 3. Créer les tables suivantes :
--
-- Table sensors :
--    - id (INT AUTO_INCREMENT PRIMARY KEY)
--    - name (VARCHAR(100) NOT NULL)
--    - type (ENUM('LEVEL', 'FLOW', 'PRESSURE') NOT NULL)
--    - location (VARCHAR(255) NOT NULL)
--    - latitude, longitude (DECIMAL)
--    - status (ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE'))
--    - installed_at, last_reading_at, created_at, updated_at (DATETIME)
--
-- Table sensor_readings :
--    - id (INT AUTO_INCREMENT PRIMARY KEY)
--    - sensor_id (INT NOT NULL, FOREIGN KEY vers sensors)
--    - value (DECIMAL(10,2) NOT NULL)
--    - unit (VARCHAR(20) NOT NULL)
--    - recorded_at (DATETIME DEFAULT CURRENT_TIMESTAMP)
--
-- Table pumps :
--    - id (INT AUTO_INCREMENT PRIMARY KEY)
--    - name (VARCHAR(100) NOT NULL)
--    - location (VARCHAR(255) NOT NULL)
--    - capacity (DECIMAL(10,2) NOT NULL) -- en m³/h
--    - status (ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'ERROR'))
--    - last_activated_at, created_at, updated_at (DATETIME)
--
-- Table alerts :
--    - id (INT AUTO_INCREMENT PRIMARY KEY)
--    - sensor_id (INT, FOREIGN KEY vers sensors)
--    - alert_type (ENUM('HIGH_LEVEL', 'LOW_LEVEL', 'SENSOR_ERROR', 'PUMP_ERROR'))
--    - severity (ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
--    - message (TEXT NOT NULL)
--    - status (ENUM('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED'))
--    - threshold_value, current_value (DECIMAL(10,2))
--    - created_at, acknowledged_at, resolved_at (DATETIME)
--
-- Table pump_operations :
--    - id (INT AUTO_INCREMENT PRIMARY KEY)
--    - pump_id (INT NOT NULL, FOREIGN KEY vers pumps)
--    - operation_type (ENUM('START', 'STOP', 'MAINTENANCE'))
--    - performed_by (VARCHAR(100))
--    - notes (TEXT)
--    - created_at (DATETIME)
--
-- 4. Créer les index pour optimiser les requêtes :
--    - idx_sensor_readings_sensor_id
--    - idx_sensor_readings_recorded_at
--    - idx_alerts_status
--    - idx_alerts_severity
--    - idx_pumps_status
